document.addEventListener('DOMContentLoaded',()=>{
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.12});
  document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
  const menu=document.querySelector('.mobile-nav'), trigger=document.querySelector('.menu-trigger');
  trigger?.addEventListener('click',()=>{const open=menu.classList.toggle('open');trigger.setAttribute('aria-expanded',open)});
  menu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('open');trigger.setAttribute('aria-expanded','false')}));
  const cursor=document.querySelector('.cursor'), follower=document.querySelector('.cursor-follower');
  if(window.matchMedia('(pointer:fine)').matches){document.addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';follower.style.left=e.clientX+'px';follower.style.top=e.clientY+'px'})}
  const studies={commerce:{title:'Commerce Engine',overview:'A complete storefront experience built around the core flows people expect from online shopping.',problem:'The project needed to feel like a real shop rather than a collection of disconnected screens.',solution:'I structured the experience around clear product discovery, account, cart, checkout, and support journeys.',highlights:['Responsive catalog and product pages','Cart and checkout interaction patterns','Account, FAQ, and contact flows'],demo:'e-commerce-site/index.html'},flow:{title:'Flow Manager',overview:'A focused task management workspace for planning work, deadlines, and team momentum.',problem:'Task tools can become noisy when the essential actions are buried beneath too much interface.',solution:'I designed a compact workspace that keeps tasks, calendar, and team views easy to reach.',highlights:['Task-focused information architecture','Calendar and team workspace screens','Responsive dashboard layout'],demo:'task-manager-app/index.html'},atmosphere:{title:'Atmosphere',overview:'A weather dashboard designed to make forecasts, alerts, and conditions easy to scan.',problem:'Weather data is only useful when users can understand it quickly across locations and screen sizes.',solution:'I organized forecast, map, and alert views into a clear dashboard experience.',highlights:['Forecast and alert views','Map-focused information design','Responsive data presentation'],demo:'weather-dashboard/index.html'},vitality:{title:'Vitality',overview:'A health tracking experience for workouts, nutrition, progress, and daily consistency.',problem:'Health data can feel abstract without a simple, motivating visual overview.',solution:'I created a dashboard language that turns progress and daily activity into approachable views.',highlights:['Workout and nutrition sections','Progress dashboard patterns','Mobile-friendly tracking flows'],demo:'fitness-tracker/index.html'}};
  const dialog=document.getElementById('caseStudy'); document.querySelectorAll('.case-link').forEach(button=>button.addEventListener('click',()=>{const s=studies[button.dataset.project];document.getElementById('dialogTitle').textContent=s.title;document.getElementById('dialogOverview').textContent=s.overview;document.getElementById('dialogProblem').textContent=s.problem;document.getElementById('dialogSolution').textContent=s.solution;document.getElementById('dialogHighlights').innerHTML=s.highlights.map(item=>`<li>${item}</li>`).join('');document.getElementById('dialogDemo').href=s.demo;dialog.showModal()}));
  document.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close()); dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
  document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('.form-status').textContent='Thanks — your message is ready to send. Please email me directly for the fastest reply.';e.currentTarget.reset()});
});
