document.addEventListener('DOMContentLoaded',()=>{
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.12});
  document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
  const menu=document.querySelector('.mobile-nav'), trigger=document.querySelector('.menu-trigger');
  trigger?.addEventListener('click',()=>{const open=menu.classList.toggle('open');trigger.setAttribute('aria-expanded',open)});
  menu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('open');trigger.setAttribute('aria-expanded','false')}));
  const cursor=document.querySelector('.cursor'), follower=document.querySelector('.cursor-follower');
  if(window.matchMedia('(pointer:fine)').matches){document.addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';follower.style.left=e.clientX+'px';follower.style.top=e.clientY+'px'})}
  const studies={nexus:{title:'Nexus Catalog',overview:'A live catalog of real production websites, presented as an interactive index instead of a static project list.',problem:'A growing body of deployed work needed a clear way to browse real sites, understand their categories, and open each one directly.',solution:'Nexus Catalog organizes production sites into a browsable catalog with featured work, folder-based discovery, live previews, and direct launch links.',highlights:['Interactive catalog of deployed sites','Folder and industry-based browsing','Live previews with direct production links'],demo:'https://nexus-catalog-portfolio.vercel.app/'}};
  const dialog=document.getElementById('caseStudy'); document.querySelectorAll('.case-link').forEach(button=>button.addEventListener('click',()=>{const s=studies[button.dataset.project];document.getElementById('dialogTitle').textContent=s.title;document.getElementById('dialogOverview').textContent=s.overview;document.getElementById('dialogProblem').textContent=s.problem;document.getElementById('dialogSolution').textContent=s.solution;document.getElementById('dialogHighlights').innerHTML=s.highlights.map(item=>`<li>${item}</li>`).join('');document.getElementById('dialogDemo').href=s.demo;document.getElementById('dialogPreview').src=s.demo;document.getElementById('dialogMobilePreview').src=s.demo;dialog.showModal()}));
  document.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close()); dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
  document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const subject=encodeURIComponent(`[Portfolio] ${data.get('subject')}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('message')}`);form.querySelector('.form-status').textContent='Opening your email client with the completed message.';window.location.href=`mailto:ochemehenry24@gmail.com?subject=${subject}&body=${body}`});
});
